package "ISD" as isd {
  package "DMG Team" as dmg {
    actor "Amandeep Singh" as amandeeps
    actor "Thomas Buno" as thomasb
    actor "Manpreet Singh (Manny)" as manpreets
    actor "Florence Peng" as florencep
    actor "Julie Costa" as juliec
    actor "Min Chen" as minc
    actor "Angelina Gerasimov" as angelinag
    actor "Curtis Splan" as curtiss
  }
  package "HAB" as hab {
    actor "Whitney Carpenter" as whitneyc
    actor "Mary Holiday-Hanson" as maryhh
  }

  package "ISO" as iso {
    actor "David Ferrell" as davidf
    actor "Steven Fong" as stevenf
  }
  actor "Michael Valle" as michaelv
  actor "Manraj Singh" as manrajs
  actor "James Petersen" as jamesp
  actor "Starla Ledbetter" as starlal
  actor "Ryan Morris" as ryanm
}
