package "ISD" as isd {
  package "Data Management Group" as dmg {
    actor "Amandeep Singh" as amandeeps
    actor "Thomas Buno" as thomasb
    actor "Manpreet Singh (Manny)" as manpreets
    actor "Florence Peng" as florencep
    actor "Julie Costa" as juliec
    actor "Min Chen" as minc
    actor "Angelina Gerasimov" as angelinag
    actor "Curtis Splan\Supervisor" as curtiss
  }
  package "Healthcare Analytics Branch" as hab {
    actor "Whitney Carpenter\nResearch Data Specialist" as whitneyc
    actor "Mary Holiday-Hanson\nResearch Scientist Supervisor" as maryhh
  }

  actor "Chris Krawczyk\nChief Analytics Officer" as chrisk
  actor "Steven Sottana\nCheif Strategy Officer" as stevens
  actor "David Ferrell\nInformation Security Officer" as davidf
  actor "Michael Valle\nChief Information Officer" as michaelv
  actor "Manraj Singh\nSolutions Architect" as manrajs
  actor "James Petersen\nTechnical Architect" as jamesp
  actor "Starla Ledbetter\nChief Data Officer" as starlal
  actor "Ryan Morris\nChief Technology Officer" as ryanm
}
